name: Deploy Air Quality Dashboard

on:
  push:
    branches: [ main ]
    paths:
      - 'apps/air-quality-dashboard/**'
      - '.github/workflows/deploy-air-quality.yml'

env:
  AWS_REGION: eu-north-1
  ECR_REPOSITORY: pollution-dashboard

jobs:
  
  build-and-push:
    name: Build & Push (Air Quality)
    runs-on: ubuntu-latest

    steps:
    - name: Récupérer le code
      uses: actions/checkout@v3 
      with:
          lfs: true

    - name: Configurer les identifiants AWS
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Connexion à Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Construction et Envoi de l'image Docker
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: latest
      run: |
        cd apps/air-quality-dashboard
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG